### ISSUE TITLE
Chat webapp through IRC

### ISSUE THREAD

**Issue by sunny** [sunny/dev-ideas#22]
Like Campfire or Kandan, but over IRC. See also [Groucha](http://sourceforge.net/projects/groucha/).

**Comment by jsilvestre** [comment]
Here is a solution in NodeJS : https://github.com/cjstewart88/nirc

Still missing features like log recording (nirc doesn't actually use any storage engine to my knowledge).

**Comment by sunny** [comment]
Thanks for nirc, it's a pretty awesome start!

**Comment by nono** [comment]
There is also https://kiwiirc.com/

**Comment by sunny** [comment]
Wow, kiwiirc is just what I needed actually. Even on mobile it looks really
good. Thanks @nono
